### ISSUE TITLE
Best fit line create new graph on every data update

### ISSUE THREAD

**Issue by ikorolev1990** [amcharts/tools#10]
https://snag.gy/1DAo6e.jpg

After every data update i have to call this.chart.validateData() and AmCharts.bestFitLineProcess(this.chart, true);

And after every call of AmCharts.bestFitLineProcess(this.chart, true); i have new graph in my this.chart.graphs and new item in legend

**Comment by martynasma** [comment]
Fixed in 1.0.7

Thanks!
