### ISSUE TITLE
[bestFitLine] Issue with many graphs

### ISSUE THREAD

**Issue by shumakosik** [amcharts/tools#16]
Hello!
http://codepen.io/shumakosik/pen/EWjvNR
Why First trend (yellow)  starts at second trend's (blue) ?
And other case: http://codepen.io/shumakosik/pen/gmpxRp
First trend (blue) starts at second trend's (yellow)

**Comment by martynasma** [comment]
Thanks for the heads up.

Turns out a wrong (older) version of the plugin was cached in our CDN servers. The cache is now cleared. The trend lines appear correctly.

(make sure you clear your browser cache as well)

**Comment by shumakosik** [comment]
I'm sure that cache was cleared, but nothing has changed.
p.s. I run other browser in private mode and issue is still not fix ... 
My local server have this error too.  http://imgur.com/a/bZWMy
Version AmCharts - 3.20.20, bestFitLine - lastest from git

**Comment by martynasma** [comment]
Do you have a codepen for your last chart for me to test?

Both codepends you provided are now displaying proper trend lines after clearing:

![image](https://cloud.githubusercontent.com/assets/1458520/23398197/3b2e2dd4-fda4-11e6-8683-78bc8d507b12.png)

**Comment by shumakosik** [comment]
Hmm... http://codepen.io/shumakosik/pen/gmpxRp
Why Yellow trend line starts at USA ? In dataProvider properties "visits" are null... Yellow line should be start at Germany, no ?  
Screen: ![Alt Text](http://i.imgur.com/vLNU1sI.jpg) 
I will give you my example soon
This issue is reproduced when one of graphs values is not start from beginning

**Comment by shumakosik** [comment]
Any news of this issue?

**Comment by martynasma** [comment]
Hey,

Just release 1.0.8 which should fix the issue.

**Comment by shumakosik** [comment]
Hello!
Thanks for update. Works great.

**Comment by martynasma** [comment]
You're welcome!
