### ISSUE TITLE
Issue with many charts one page

### ISSUE THREAD

**Issue by shumakosik** [amcharts/tools#17]
Hello! I have a new problem. I use jQuery EasyUI for create many tabs. I dynamically create charts in tabs. (This example contents 3 tabs with charts, but in my project I create very many tabs) 
All tabs contents serial Amchart. I use autoOffsetAxis, but tool works not correct. Last chart in third tab correctly positione offset, but first and second not work :(
http://codepen.io/shumakosik/pen/qrovgL
ValueAxes starts works fine when you click at legend for "off/on" graph after initialization chart.
May you help me?
Thanks.

**Comment by martynasma** [comment]
Hi there.

It must be some sort of timing issue.

We just released an update. (1.4)

It adds a public method to chart object `updateOffsets()`.

I'm not familiar with EasyUI, but I bet it should have some sort of event model which you can use to call the above method on your chart objects. You might need to experiment a bit which event to use. It could be when tab is created, selected or when all tabs are created.

You need to call this method on all chart objects once.

I.e.:

```
AmCharts.charts[0].updateOffsets();
```

I hope this helps.

**Comment by shumakosik** [comment]
Thanks for answer!
I fix this problem with updateOffsets() and setTimeout function.
