### ISSUE TITLE
addGraph to polarScatter

### ISSUE THREAD

**Issue by gbayarri** [amcharts/tools#19]
Hi, I'm trying to add a graph dynamically to a polarScatter radar chart and I don't know how to load the `series` array properly. Doing it in this way doesn't work:

```
var graph = new AmCharts.AmGraph();
graph.lineColor = "#FFCC00";
graph.fillAlphas = 0.4;
graph.bullet = "triangleUp";
graph.bulletSize = 15;
graph.series = [[-93,0.05]];
chart.addGraph(graph);
chart.validateData();
```

Is it possible?

Thanks!

**Comment by martynasma** [comment]
Hi,

Just updated polarScatter plugin to 1.0.1.

It now allows data/graph updates.

After you add a graph, make sure you use `AmCharts.processPolarScatter(chart)`:

```
var graph = new AmCharts.AmGraph();
graph.lineColor = "#FFCC00";
graph.fillAlphas = 0.4;
graph.bullet = "triangleUp";
graph.bulletSize = 15;
graph.series = [[-93,0.05]];
chart.addGraph(graph);
AmCharts.processPolarScatter(chart);
chart.validateNow(true);
```

Also note, I'm using `validateNow(true)` instead of `validateData()`.

Hope this helps.

**Comment by gbayarri** [comment]
Thanks, that was exactly what I needed!

I have to put a guide, too. But not an area guide as you have in your examples, just one line from the center of the chart to the last circle with a given angle. As a grid, but with a color and a label (if it is not possible, it could be shown in the legend area). Should I open a new issue, or can you give me an answer in that threat?

Thank you!

**Comment by martynasma** [comment]
Glad that worked well.

As for guides, there's no way to have a thin straight line. You can have a guide with a very small difference between `angle` and `toAngle`, though.

https://codepen.io/team/amcharts/pen/af1f617703c8a58df412f21afebec3f8?editors=0010

May you find that useful.

**Comment by gbayarri** [comment]
Hi Martynas, thanks for your fast answer. That was just I've tried, but I can't put a label here as we do in the serial charts.

Anyway, thanks for your help!

**Comment by martynasma** [comment]
Well, not sure about any other workarounds :(

**Comment by gbayarri** [comment]
Finally I'm using the angle guide you provided and after, I change the label position via JS.

Thanks for everything.
