### ISSUE TITLE
Package manager

### ISSUE THREAD

**Issue by JensMakeable** [amcharts/tools#24]
I am trying to use bestFitLine in my project that imports scripts through bower and npm.

Are these tools available in a package manager like those, or would you consider publishing them in such?

**Comment by martynasma** [comment]
Hi Jens,

I'm afraid plugins in this github repo are not available as a npm package.

You can still install them directly from GitHub though.

**Comment by JensMakeable** [comment]
Thanks a lot, actully didn't know that was possible :-)
