### ISSUE TITLE
[smoothCustomBullets] Don't work with multiple graphs

### ISSUE THREAD

**Issue by Silbad** [amcharts/tools#25]
Hello,
I have an issue with several graphs

`	
	      "graphs": [
                    {
                        "valueAxis": "v1",
                        "balloonText": "[[title]] : <b>[[value]] km</b>",
                        "fillAlphas": 0.9,
                        "lineAlpha": 0.2,
                        "lineColor": "#b3dfe2",
                        "type": "column",
                        "valueField": "Value1"
                    },
                    {
                        "valueAxis": "v2",
                        "balloonText": "[[title]] : <b>[[value]]h</b>",
                        "fillAlphas": 0.9,
                        "lineAlpha": 0.2,
                        "lineColor": "#45b9bf",
                        "type": "column",
                        "clustered": false,
                        "columnWidth": 0.5,
                        "valueField": "Value2"
                    },
		            {
		                "valueAxis": "v3",
		                "balloonText": "[[title]] : <b>[[value]]</b>",
		                "fillAlphas": 0,
		                "lineAlpha": 0.6,
		                "lineColor": "#5d5b5e",
		                "valueField": "Value3",
		                "bullet": "round",
		                "customBulletField": "PhotoUrl",
		                "bulletSize": 40,
		                "bulletOffset": 18,
		                "labelPosition": "right",
                        "labelText": "[[value]]"
		            }
		        ],
`
=> dataPoint is undefined
With just one graph, it's ok ;)
Thanks

**Comment by martynasma** [comment]
Merged your commit. Let us know if you still having the issue.

**Comment by Silbad** [comment]
Nope it's ok ^^
For your information, I haven't changed the version number and the min file ;)

**Comment by martynasma** [comment]
No worries. I did ;)

Thanks again!
