### ISSUE TITLE
Update for v4

### ISSUE THREAD

**Issue by isar-andrei** [amcharts/tools#28]
Hello, is there a plan to update the tool to work with the amcharts4?

**Comment by martynasma** [comment]
Those are collection of plugins for amCharts 3.

Some of the functionality is built-in in amCharts 4. Others might be implemented as plugins at some point. (no ETA yet)

**Comment by isar-andrei** [comment]
Thanks for the quick reply, to be more specific, the tool I'm most interested in is bestFitLine, is it built-in into v4 or are there any plans to implement it as a plugin in the future?

**Comment by martynasma** [comment]
No, I'm afraid there are no such technical indicators built-in in amCharts 4.

At this time we do not plan on porting this plugin over, either. We're still dealing with post-release rush of support/fixes.

In 2019, when the dust settles, you'll start seeing plugins popping up. We will consider porting this plugin then.

**Comment by isar-andrei** [comment]
Thanks, I will keep an eye on it in the future.
