### ISSUE TITLE
[datepadding] Problem with empty dataprovider

### ISSUE THREAD

**Issue by zeljkou** [amcharts/tools#9]
Similar to  bestFitLine if dataprovider is empty, datapadding throws error. Everything works fine without it.
(http://localhost:3000/assets/amcharts/plugins/datePadding/datePadding.js:105:22)
    at Object.AmCharts.datePaddingProcess (http://localhost:3000/assets/amcharts/plugins/datePadding/datePadding.js:235:3)
    at Object.method (http://localhost:3000/assets/amcharts/plugins/datePadding/datePadding.js:299:13)

```
function processData( axis, dataProvider, categoryField, dataDateFormat ) {

    // get first and last dates, min period in milliseconds
    var firstDate = getDate(
            dataProvider[ 0 ][ categoryField ],
            dataDateFormat ),
        lastDate = getDate(
            dataProvider[ dataProvider.length - 1 ][ categoryField ],
            dataDateFormat ),
        sampleFormat = dataProvider[ 0 ][ categoryField ];
```

**Comment by martynasma** [comment]
Hi there,

Just released an update which fixes this issue.

**Comment by zeljkou** [comment]
thank you
